# Generated by Django 2.0.5 on 2018-06-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epis_web', '0003_auto_20180602_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitocurso',
            name='curso_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso_asignado', to='epis_web.Curso'),
        ),
        migrations.AlterField(
            model_name='requisitocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='epis_web.Curso'),
        ),
    ]
