# Generated by Django 2.0.5 on 2018-06-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epis_web', '0004_auto_20180602_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitocurso',
            name='curso_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso_asignado', to='epis_web.Curso'),
        ),
        migrations.AlterField(
            model_name='requisitocurso',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
