# Generated by Django 2.0.5 on 2018-06-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis_web', '0005_auto_20180602_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitocurso',
            name='nombre',
        ),
        migrations.AddField(
            model_name='requisitocurso',
            name='credito',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
