# Generated by Django 2.0.5 on 2018-06-02 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epis_web', '0006_auto_20180602_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConsurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaConcurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('resena', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Consurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=300)),
                ('resena', models.CharField(max_length=500)),
                ('lugar', models.CharField(max_length=100)),
                ('lugar_url', models.CharField(max_length=500)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='descripcion',
            new_name='resena',
        ),
        migrations.AlterField(
            model_name='imagenproyecto',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoriaconcurso',
            name='concurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epis_web.Consurso'),
        ),
        migrations.AddField(
            model_name='baseconsurso',
            name='concurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epis_web.Consurso'),
        ),
    ]
