# Generated by Django 2.0.5 on 2018-06-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epis_web', '0008_auto_20180602_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='epis_web.CategoriaConcurso'),
            preserve_default=False,
        ),
    ]
