# Generated by Django 2.0.5 on 2018-06-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis_web', '0010_auto_20180602_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproyecto',
            name='url',
        ),
        migrations.AddField(
            model_name='imagenproyecto',
            name='imagen',
            field=models.ImageField(default='static/epis_Web/image.png', upload_to='static/epis_Web/'),
        ),
    ]
